title:            Nick Patch
email:            patch@cpan.org
description:      Open source, written languages of the worldâ€¦ and lichens!
baseurl:          ""
url:              http://nickpatch.net
twitter_username: nickpatch
github_username:  patch
encoding:         utf-8
markdown:         kramdown
timezone:         America/New_York
